### PR TITLE
kernel: fix 9p fs unlink-ftruncate

### PR DESCRIPTION
**Pull request by devimc**
Fixes https://github.com/01org/cc-oci-runtime/issues/152
Fixes https://github.com/01org/cc-oci-runtime/issues/1062

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by mcastelino** [comment]
@devimc can you run a stress test on this. Create and delete a large number of containers. Last time we tried this change we periodically saw that the host side unmount issues... even after qemu was terminated.

**Comment by devimc** [comment]
@mcastelino sure, I can run the stress test

**Comment by mcastelino** [comment]
@devimc we also tried an alternative way to fix this 
https://github.com/clearcontainers/agent/pull/93/files

But that resulted in hanging mounts.

@chavafg can we add this test to our CI. As we seemed to have missed this kind of test.

**Comment by devimc** [comment]
@chavafg @mcastelino  would be nice to run all docker test twice but with different storage driver (devicemapper and overlay)

**Comment by devimc** [comment]
stress test results using default clear containers kernel (no 9p patch) https://github.com/clearcontainers/runtime/issues/570

**Comment by chavafg** [comment]
@mcastelino: @grahamwhaley has opened https://github.com/clearcontainers/tests/pull/491 which verifies that the CC components have ended successfully after deleting the containers, Graham, can you add a step there to check if there are mounted paths left behind?

**Comment by grahamwhaley** [comment]
@chavafg That's a good idea. Hopefully we can do that in a way that caters for different storage drivers as well (if that makes a difference).
Let me add a note over on that PR, or I'll forget...

**Comment by chavafg** [comment]
Thanks @grahamwhaley

**Comment by devimc** [comment]
running the same test of https://github.com/clearcontainers/runtime/issues/570 but using a kernel with this patch, I don't see any instance of qemu running and all rootfs have been unmounted

```
$ ps -ef | grep qemu
fedora   31233  1356  0 09:34 pts/1    00:00:00 grep --color=auto qemu
```
```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
```
$ mount  | grep "docker" 
/dev/mapper/fedora-root on /var/lib/docker/overlay type xfs (rw,relatime,attr2,inode64,noquota)
```

**Comment by grahamwhaley** [comment]
@devimc would you be able to run the script from:
https://github.com/clearcontainers/tests/pull/491
? It sanity checks iirc both during launch and post rm for all cc components.

**Comment by devimc** [comment]
@grahamwhaley   :(

```
docker: Error response from daemon: service endpoint with name gifted_clarke already exists.
Checking 38 containers have all relevant components
Wrong number of shims running (38*2 != 74 - stopping
```

**Comment by grahamwhaley** [comment]
Thanks @devimc.
This is an odd error though:
`docker: Error response from daemon: service endpoint with name gifted_clarke already exists.`
If that had said the container name was already in use then I would have thought we'd picked up some junk from a previous failed run - but - that `gifted_clarke` is one of dockers automated generated names by the look of it. That is very odd.
I think that would need somebody to dig into the runtime logs to see what happened maybe...

**Comment by gorozco1** [comment]
@devimc Please add a brief description in the PR and in the commit to know why this PR is needed.

**Review by gorozco1 — APPROVED** [review]

**Pull request merged**
