### PR TITLE
kernel: Add kernel config for ACPI hotplug

### LINKED ISSUE #168: Add kernel config for ACPI hotplug.

### PR DESCRIPTION
**Pull request by amshinde**
This is needed for hotplugging devices based on
ACPI hotplug mechanism.

Fixes #168

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
@amshinde I guess this is needed for hotplugging drives into qemu with the pc machine type ?

**Comment by amshinde** [comment]
@sameo Yes, thats right.

**Comment by sameo** [comment]
@amshinde Please also see https://github.com/containers/virtcontainers/pull/433
Without this PR, we were always mounting the pause dm device into the container rootfs when running on top of CRI-O or k8s.

**Comment by sameo** [comment]
@amshinde I will give your patch a try tomorrow morning.

**Comment by sameo** [comment]
LGTM

**Review by sameo — APPROVED** [review]

**Pull request merged**
