### PR TITLE
kernel: use the maximum number of CPUs

### LINKED ISSUE #198: unable to online more than 8 vCPUs
in order to honour CPU constraints in the POD, the agent should be able to online more than 8 vCPUs

### LINKED ISSUE #255: unable to online more than 8 vCPUs
see https://github.com/clearcontainers/agent/issues/198

### PR DESCRIPTION
**Pull request by devimc**
since we don't know how many CPUs can have the host, we should
use the maximum number of CPUs supported by KVM (240)

255 is the maximum number of CPUs supported in the kernel, but the
maximmum number of CPUs recommended by KVM is 240, if more than 240
CPUs are used, next error will be returned by Qemu

Number of hotpluggable cpus requested (255) exceeds the recommended cpus supported by KVM (240)

fixes #255
fixes https://github.com/clearcontainers/agent/issues/198

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Gotta ask - did you wait until you could create issue 255 or did you just "get lucky"? :smile:

This seems to replace #175 right?

**Comment by devimc** [comment]
@jodh-intel  \o/ , I just got lucky
yes this is to replace #175

**Comment by jcvenegas** [comment]
lgtm , lets just increase the release number in one of your PRs to include both changes in the same kernel release.

**Comment by devimc** [comment]
@jcvenegas changes applied, thanks

**Comment by devimc** [comment]
can we merge this pr?

**Comment by jodh-intel** [comment]
lgtm.

We might want to get another ack from @grahamwhaley and/or @mcastelino though.

**Comment by devimc** [comment]
so, any update on this ?

**Review by mcastelino — APPROVED** [review]
LGTM

**Pull request merged**
