### PR TITLE
packages: update runtime, shim and proxy to 3.0.0 release.

### LINKED ISSUE #113: Update packages to 3.0.0 release

### PR DESCRIPTION
**Pull request by erick0z**
Update packages (cc-runtime, cc-proxy, cc-shim) to 3.0.0.

Fixes #113

### CODE REVIEW

**Comment by egernst** [comment]
Woohoo!

**Comment by gorozco1** [comment]
@chavafg could you take a look?

**Review by gorozco1 — APPROVED** [review]
lgtm

**Comment by gorozco1** [comment]
http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/

**Comment by chavafg** [comment]
lgtm

**Pull request merged**
