### PR TITLE
kernel: Update linux-container to 4.9.47

### PR DESCRIPTION
**Pull request by gorozco1**
This updates the linux-container kernel to the latest long-term kernel
available. 4.9.47

Fixes: #80

Signed-off-by: Geronimo Orozco <geronimo.orozco@intel.com>

### CODE REVIEW

**Comment by gorozco1** [comment]
New packages for the linux-container kernel available in the staging repo ready for PnP.

http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3-staging/

**Comment by miguelinux** [comment]
Good job @gorozco1 

http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3-staging/CentOS_7/x86_64/linux-container-4.9.45-77.1.x86_64.rpm
http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3-staging/Fedora_26/x86_64/linux-container-4.9.45-77.1.x86_64.rpm
http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3-staging/SLE_12_SP3/x86_64/linux-container-4.9.45-77.1.x86_64.rpm
http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3-staging/xUbuntu_16.04/amd64/linux-container_4.9.45-77_amd64.deb
http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3-staging/xUbuntu_17.04/amd64/linux-container_4.9.45-77_amd64.deb

**Review by miguelinux — APPROVED** [review]
lgtm

**Comment by jodh-intel** [comment]
Typo in commit message: `s/logterm/long-term/`

**Comment by gorozco1** [comment]
Fix typo thanks for the note @jodh-intel

**Comment by jodh-intel** [comment]
lgtm

**Comment by gorozco1** [comment]
@chavafg could you test this kernel before release with the other components?

**Comment by chavafg** [comment]
@gorozco1 The functionality is ok, there is just a minor issue with the kernel version showed inside the Container. More info on: https://github.com/clearcontainers/packaging/issues/87

**Pull request merged**
