### PR TITLE
kernel: update to 4.9.60

### LINKED ISSUE #181: Update kernel to version 4.9.60
Update kernel in this also requires to update the package in Clear Linux update and tag 
https://github.com/clearcontainers/linux.

### PR DESCRIPTION
**Pull request by miguelinux**
Update Linux kernel to v4.9.60 stable version

Fixes #181

Signed-off-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
@miguelinux  dont  you need to update the kernel version in `versions.txt` ? and `debian.changelog` should be modified after build obs packages ?

**Comment by jcvenegas** [comment]
@erick0z could you take a look to this PR?

**Comment by erick0z** [comment]
@miguelinux Can you update the versions.txt? Normally, we send the PR after the package has been sent and tested in the non-staging repo, so the debian.changelog match the official package.

**Comment by miguelinux** [comment]
@erick0z the new obs repo is updated.

@jcvenegas Do I need to update versions.txt or  Is it updated ones a CC v3.0 has new release?

**Comment by jodh-intel** [comment]
Hi @erick0z - can you either create a `docs/process.md` file explaining the process about updating the `versions.txt` file, or put something in the packaging wiki: https://github.com/clearcontainers/packaging/wiki.

**Comment by miguelinux** [comment]
@erick0z version is updated

**Comment by erick0z** [comment]
lgtm

**Review by erick0z — APPROVED** [review]
lgtm

**Pull request merged**
