### PR TITLE
Make opensuse build

### LINKED ISSUE #36: OpenSUSE packages not provided
Currently we do not provide OpenSUSE packages.

At least we need to provide packages for OpenSUSE Tumbleweed

### PR DESCRIPTION
**Pull request by thiagomacieira**
I've got OpenSUSE Tumbleweed building at https://build.opensuse.org/project/show/home:thiagomacieira:branches:home:clearcontainers:clear-containers-3-staging

Fixes #36

### CODE REVIEW

**Comment by thiagomacieira** [comment]
Each of the commits updates multiple subsystems, like a6e9e1ee3d5dd24ea5fa315b4375115a56d3456c. Any way to convince Travis to accept it anyway?

**Comment by gorozco1** [comment]
@thiagomacieira Thanks a lot for this PR. The missing part on the commit and the PR is the word Fixes:

You need to add

Fixes #37  to make travis happy


#37 is the issue I filed yesterday related to this.

**Comment by gorozco1** [comment]
@thiagomacieira oh, and I noticed that you are trying to push 3 commits.

Could you squash them in a single commit and add the issue the commit fixes (In this case #37 )

It is recommended that each of your patches fixes one thing, so in this case your 3 commits fixes one single issue. So better be in a single squashed commit.

**Comment by thiagomacieira** [comment]
Well, each of the patches fixes one problem with the .spec files. Building for OpenSUSE wasn't a simple fix.

Do you really want me to squash?

**Comment by gorozco1** [comment]
@thiagomacieira oh, if each of the commits fixes an issue could you please create issuesand then reference the issue fixed in each of the commits as: Fixes: #XX

**Comment by thiagomacieira** [comment]
#36 is a "meta" task. I am saying that there were three different problems in providing OpenSUSE packages.

Do you want me to file three issues for the small details that I discovered, fix each with one commit, then close #36?

**Comment by gorozco1** [comment]
@thiagomacieira, 

On a closer look I found that travis is complaining that your commits does not have a `subsistem` in the subject.

`Failed to find subsystem in subject: "Update .spec files to add BuildRequires for OpenSUSE"`

From https://github.com/clearcontainers/tests/tree/master/cmd/checkcommits

> The commit subject contains a "subsystem" (adjust using --subject-length=). A "subsystem" is simply one or more words followed by a colon at the start of the subject and designed to identify the area of the code the change applies to.


Could you try to rephrase  the subject in your commits with something like:

- opensuse: Add directory names to the %file listing 
- opensuse: Update libexec dirs to match OpenSUSE installation guidelines
- opensuse: Update .spec files to add BuildRequires for OpenSUSE

**Review by gorozco1 — APPROVED** [review]
lgtm

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
