### PR TITLE
packages: Apport hook

### LINKED ISSUE #135: Add apport hook for Ubuntu packages
[source_cc-runtime.py.txt](https://github.com/clearcontainers/packaging/files/1358686/source_cc-runtime.py.txt)

To make it easier for users to report problems, we should add an apport hook to the following Ubuntu packages:

- `cc-proxy`
- `cc-runtime`
- `cc-shim`
- `qemu-lite`

I've attached the basic hook which will call the `cc-collect-data.sh` script when any of the components above crashes. The script output will then be added to the standard Ubuntu bug report that will get created on launchpad.net.

The hook needs to be installed on Ubuntu systems only to the following directory:

```
/usr/share/apport/package-hooks/
```
The name of the hook is also important. The format we need to use is `source_${package_name}.py`. This will guarantee that when any program in any package that was *generated from* the source `${package_name}` package crashes, the hook will be triggered. Although we could potentially create symlinks for `source_cc-shim.py`, `source_cc-proxy.py` and `source_qemu-lite.py`, that might be actually rather tricky due to the package dependencies: the runtime depends on the other elements rather than the other way round. If the elements depended on the runtime, it would be easy for each package to create a sym-link to `source_cc-runtime.py` as that package would have already installed its apport hook. However, that isn't possible currently.

As such, and since it is such a simple script that probably won't change, I think the best solution is to simply copy the hook to the different packages and give it the correct name. The packaging scripts could still have a single copy of the hook and create it with the correct name at package build time of course.

### PR DESCRIPTION
**Pull request by erick0z**
This set of commits adds the Apport hook for Ubuntu packages.

Fixes #135

Note: Added separate commits for better review. Can be squashed once reviewed.

### CODE REVIEW

**Review by gorozco1 — COMMENTED** [review]
@erick0z AFAIK this change was only for debian/ubuntu based distros. Did you test it on RH based distros?

**Comment by erick0z** [comment]
@gorozco1 Packages were successfully built, anyway, I've now removed the changes from the spec files. Just shipping on Ubuntu packages.

**Review by gorozco1 — APPROVED** [review]
lgtm

**Comment by jodh-intel** [comment]
Thanks guys!! :smile:

**Pull request merged**
